spring.application.name=api

spring.jackson.deserialization.fail-on-unknown-properties=false
spring.jackson.deserialization.fail-on-null-for-primitives=false
goldapi.key=goldapi-05fa6bf38786a5be536d735c37968b03-io
